import MailSentVacanciesByEmployee from "./components/MailSentVacanciesByEmployee";
import AllCompletedVacancies from "./pages/AllCompletedVacancies";

export const Routes = {
    // pages
    // Presentation: { path: "/" },
    DashboardOverview: { path: "/" },
    Transactions: { path: "/transactions" },
    Settings: { path: "/settings" },
    Vacancy: { path: "/add-vacancy" },
    TotalAllotedVacancies:{path:'/alloted-vacancies'},
    TotalPendingVacancies:{path:'/pending-vacancies'},
    MailSentVacanciesByEmployee:{path:'/mail-sent'},
    Employer: { path: "/add-company" },
    Candidate: { path: "/add-candidate" },
    CandidateList: { path: "/candidate-list" },
    EditCandidate: { path: "/edit-candidate/:id" },
    CandidateDetail: { path: "/candidate-detail/:id" },
    CandidateShortListedByJob:{path:"/candidate-shortlisted/:id"},
    AllCompletedVacancies:{path:"/allCompletedVacancies"},
    EmployeeList: { path: "/employee-list" },
    EditEmployee: { path: "/edit-employee/:id" },
    EmployeeDetail: { path: "/employee-detail/:id" },
    CompanyList: { path: "/company-list" },
    CompanyDetail: { path: "/company-detail/:id" },
    EditCompany: { path: "/edit-company/:id" },
    VacancyList: { path: "/vacancy-list" },
    EditVacancy: { path: "/edit-vacancy/:id" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/examples/sign-in" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },
    AddEmployee:{path:'/add-employee'},

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    // Accordions: { path: "/components/accordions" },
    // Alerts: { path: "/components/alerts" },
    // Badges: { path: "/components/badges" },
    // Widgets: { path: "/widgets" },
    // Breadcrumbs: { path: "/components/breadcrumbs" },
    // Buttons: { path: "/components/buttons" },
    // Forms: { path: "/components/forms" },
    // Modals: { path: "/components/modals" },
    // Navs: { path: "/components/navs" },
    // Navbars: { path: "/components/navbars" },
    // Pagination: { path: "/components/pagination" },
    // Popovers: { path: "/components/popovers" },
    // Progress: { path: "/components/progress" },
    // Tables: { path: "/components/tables" },
    // Tabs: { path: "/components/tabs" },
    // Tooltips: { path: "/components/tooltips" },
    // Toasts: { path: "/components/toasts" },
    // WidgetsComponent: { path: "/components/widgets" }
};